### ISSUE TITLE
Wrong default remote URL

### ISSUE THREAD

**Issue by joze144** [elixytics/ref_inspector#3]
When downloading default database, I get an Error instead of correct data.

I fixed it by changing `upstream_remote` value to:
```
@upstream_remote "https://s3-eu-west-1.amazonaws.com/snowplow-hosted-assets/third-party/referer-parser/referers-latest.yaml"
```

Notice ending `.yaml` instead of currently set `.yml`

**Comment by joze144** [comment]
Actually if anyone else has an issue, can just add fixed url to the config:

```
config :ref_inspector,
       remote_urls: [{"referers.yml", "https://s3-eu-west-1.amazonaws.com/snowplow-hosted-assets/third-party/referer-parser/referers-latest.yaml"}]
```

Also thank you for the project, very cool.

**Comment by mneudert** [comment]
Thank you for noticing this!

I just released a patch with the new location. Totally missed that they have updated their documentation with that slight change :sweat_smile:
