### ISSUE TITLE
Bump hex.pm package

### ISSUE THREAD

**Issue by achedeuzot** [elixytics/ref_inspector#4]
Hello 👋 

I'm using both `ua_inspector` and would like to use `ref_inspector`. During a docker image build, I run `mix ua_inspector.download --force` so that I can package the database into the release image. It works well.
I recently added `ref_inspector` and was hoping to run `mix ref_inspector.download --force` but it crashes because it's running the app and the app is expecting some runtime.exs environment variables to be present because the mix task is using `start_app` instead of `load_app`. 

This has been fixed on master but there's no new release since 2020. Is it possible to package a more up to date `ref_inspector` and deploy it to hex.pm ? If I can help, please don't hesitate to reply. Thanks so much for your work ❤️

**Comment by mneudert** [comment]
I agree that it is high time to get a new release out.

Will take some cleanup with the partial move to a "less application more library" state. Plans are to have sort of named databases to have allow usage of multiple separate files, e.g. one for internals and one for externals.

But as the public interface contains all the necessary options already it should be possible to implement that in a fully backwards compatible way :thinking:

**Comment by mneudert** [comment]
Just released the new `v2.0.0`. Please report errors if you find any :)
